# Set prefix (default is C-b)
set -g prefix C-b

# Set hot reload keybind
unbind r
bind r source-file ~/.tmux.conf

# Set tmux path (specifically for MacOS brew installation)
set-environment -g PATH "/usr/local/bin:/bin:/usr/bin"

# Appearance & theme
set-option -g status-position top
set -ga terminal-overrides ",*256col*:Tc"
source-file ~/.tokyonight_moon.tmux

# Mouse behavior
setw -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Use vi motions in copy mode (prefix+[)
setw -g mode-keys vi

# Keybindings (use -n to replace prefix binding requirement)
bind-key n new-window
bind-key - split-window
bind-key = split-window -hf
bind v copy-mode
bind 1 select-window -t 1
bind 2 select-window -t 2
bind 3 select-window -t 3
bind 4 select-window -t 4
bind 5 select-window -t 5

# Plugins (prefix+I to install)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Don't drop out of copy mode after copy
set -g @yank_action 'copy-pipe'

# Also add status bar indication for copy and sync modes
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_show_sync_mode 'on'

# Initialize TMUX plugin manager (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
